import {StyleSheet} from 'react-native';
import {
  responsiveFontSize,
  responsiveHeight,
  responsiveScreenFontSize,
  responsiveScreenHeight,
  responsiveScreenWidth,
} from '../../Components/Utility/ResponsiveDimensions/Responsive';

export const Styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: 'white',
  },
  headerContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    height: responsiveScreenHeight(8),
    width: responsiveScreenWidth(100),
    backgroundColor: '#fafafa',
  },
  iconLeftContainer: {
    width: responsiveScreenWidth(16),
    justifyContent: 'center',
    alignItems: 'center',
  },
  searchSectionContainer: {
    flexDirection: 'row',
    width: responsiveScreenWidth(56),
    height: responsiveScreenHeight(6),
    justifyContent: 'space-evenly',
    alignItems: 'center',
    backgroundColor: 'white',
  },
  searchText: {
    fontSize: responsiveScreenFontSize(2.1),
    color: '#3c595a',
    maxWidth: responsiveScreenWidth(45),
  },
  boxAndCompareIconContainer: {
    flexDirection: 'row',
    width: responsiveScreenWidth(27),
    justifyContent: 'space-evenly',
    alignItems: 'center',
  },
  scrollViewContainer: {
    flexDirection: 'row',
    height: responsiveScreenHeight(9),
    justifyContent: 'space-evenly',
    alignItems: 'center',
  },
  filterContainer: {
    flexDirection: 'row',
    backgroundColor: '#b8f7f2',
    height: responsiveScreenHeight(6),
    width: responsiveScreenWidth(27),
    borderRadius: 25,
    borderColor: '#46beb0',
    borderWidth: 1,
    justifyContent: 'space-evenly',
    alignItems: 'center',
    marginHorizontal: responsiveScreenWidth(1.5),
  },
  selectionButtonContainer: {
    flexDirection: 'row',
    backgroundColor: '#b8f7f2',
    flex: 1,
    paddingHorizontal: responsiveScreenWidth(4),
    borderRadius: 25,
    borderColor: '#46beb0',
    borderWidth: 1,
    justifyContent: 'space-evenly',
    alignItems: 'center',
    marginHorizontal: responsiveScreenWidth(1.5),
  },
  searchResultContainer: {
    flexDirection: 'row',
    height: responsiveScreenHeight(9),
    alignItems: 'center',
  },
  resultText: {
    fontSize: responsiveScreenFontSize(2.3),
    maxWidth: responsiveScreenWidth(55),
    marginHorizontal: responsiveScreenWidth(4),
    color: '#2d5358',
  },
  sortName: {
    fontSize: responsiveScreenFontSize(2.3),
    fontWeight: 'bold',
    maxWidth: responsiveScreenWidth(50),
    color: '#072c30',
  },
  adNumbersContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'flex-end',
  },
  adNumbersMain: {
    backgroundColor: '#023034',
    width: responsiveScreenWidth(32),
    height: responsiveScreenHeight(3.5),
    justifyContent: 'center',
    alignItems: 'center',
    marginHorizontal: responsiveScreenWidth(4),
    borderRadius: 20,
  },
  adNumbers: {
    color: 'white',
    fontWeight: 'bold',
    fontSize: responsiveScreenFontSize(2.2),
  },
  renderItemContainer: {
    width: responsiveScreenWidth(50),
    height: responsiveScreenHeight(27),
    alignItems: 'center',
  },
  renderItemContent: {
    borderWidth: 0.2,
    borderRadius: 0.3,
    borderColor: '#b3b3b3',
    width: responsiveScreenWidth(46),
    height: responsiveScreenHeight(25),
  },
  imgBackground: {
    width: responsiveScreenWidth(46),
    height: responsiveScreenHeight(13),
  },
  insideContainer: {
    flexDirection: 'row',
    marginHorizontal: responsiveHeight(1),
    marginVertical: responsiveHeight(1),
  },
  featuredTextContainer: {
    backgroundColor: '#ffce38',
    width: responsiveScreenWidth(13),
    height: responsiveScreenHeight(2.6),
    justifyContent: 'center',
  },
  featuredText: {
    fontSize: responsiveFontSize(1.1),
    textAlign: 'center',
  },
  iconContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'flex-end',
  },
  iconMain: {
    width: responsiveScreenHeight(3.2),
    height: responsiveScreenHeight(3.2),
    backgroundColor: 'black',
    borderRadius: 15,
    justifyContent: 'center',
    alignItems: 'center',
  },
  rsStyle: {
    fontSize: responsiveFontSize(2),
    fontWeight: 'bold',
    paddingTop: responsiveHeight(1),
    marginHorizontal: responsiveHeight(0.6),
  },
  flexContainer: {
    flex: 1,
    justifyContent: 'space-around',
  },
  description: {
    fontSize: responsiveFontSize(2),
    marginHorizontal: responsiveHeight(0.7),
    marginVertical: responsiveHeight(0.8),
    maxWidth: responsiveScreenWidth(50),
    color: '#2a4b4e',
    fontWeight: 'bold',
  },
  rowContainer: {
    flexDirection: 'row',
    marginHorizontal: responsiveHeight(0.7),
  },
  dateContainer: {
    flex: 1,
    justifyContent: 'flex-end',
    alignItems: 'flex-end',
  },
  locationStyle: {
    fontSize: responsiveFontSize(1.5),
    maxWidth: responsiveScreenWidth(40),
    color: '#2a4b4e',
  },
});
