import {StyleSheet} from 'react-native';
import {
  responsiveFontSize,
  responsiveHeight,
  responsiveScreenHeight,
  responsiveScreenWidth,
  responsiveWidth,
} from '../../Components/Utility/ResponsiveDimensions/Responsive';

export const Styles = StyleSheet.create({
  renderContainer: {
    paddingVertical: responsiveScreenHeight(2),
    paddingHorizontal: responsiveWidth(8),
    width: responsiveScreenWidth(100),
  },
  renderText: {
    color: '#637777',
    fontSize: responsiveFontSize(2.2),
  },
  routeNameContainer: {
    flexDirection: 'row',
    height: responsiveScreenHeight(8),
    justifyContent: 'space-evenly',
    alignItems: 'center',
  },
  routeName: {
    color: '#0b2a2e',
    fontWeight: 'bold',
    fontSize: responsiveFontSize(2.5),
  },
  flatList: {
    height: responsiveScreenHeight(82),
  },
  conditions: {
    width: responsiveScreenWidth(22),
    height: responsiveScreenHeight(6.5),
    justifyContent: 'center',
    alignItems: 'center',
    borderRadius: responsiveHeight(1),
  },
  scrollView: {
    flex: 1,
  },
  imgBackContainer: {
    justifyContent: 'center',
    alignItems: 'center',
  },
  imgBack: {
    width: responsiveScreenWidth(92),
    height: responsiveScreenHeight(19),
    overflow: 'hidden',
    borderRadius: 9,
  },
  addImgesContainer: {
    backgroundColor: '#3ae5da',
    justifyContent: 'center',
    alignItems: 'center',
  },
  main: {
    backgroundColor: '#218386',
    height: responsiveScreenHeight(20),
    width: responsiveScreenWidth(82),
    borderRadius: responsiveHeight(10),
    justifyContent: 'center',
    alignItems: 'center',
  },
  iconContainer: {
    flexDirection: 'row',
    height: responsiveScreenHeight(20),
    alignItems: 'center',
    width: responsiveScreenWidth(40),
    justifyContent: 'space-evenly',
  },
  addImg: {
    fontSize: responsiveFontSize(2.5),
    fontWeight: 'bold',
    color: 'white',
  },
  price: {
    width: 70,
    textAlign: 'center',
    textAlignVertical: 'bottom',
    color: '#889897',
    fontWeight: 'bold',
  },
  inputContainer: {
    alignItems: 'center',
  },
  input: {
    width: responsiveScreenWidth(92),
    height: responsiveScreenHeight(7),
    borderRadius: 6,
    borderWidth: 1,
    borderColor: '#183338',
    textAlignVertical: 'center',
  },
  tabletsFlatList: {
    width: responsiveScreenWidth(92),
    marginHorizontal: responsiveScreenWidth(4),
  },
  feulTxt: {
    width: responsiveScreenWidth(19.5),
    textAlign: 'center',
    color: 'black',
    fontWeight: 'bold',
  },
  conditionTxtContainer: {
    justifyContent: 'flex-end',
  },
  conditionTxt: {
    width: responsiveScreenWidth(27),
    textAlign: 'center',
    height: responsiveScreenHeight(2.3),
    color: '#183338',
    fontWeight: 'bold',
  },
  conditionSelector: {
    flexDirection: 'row',
    width: responsiveScreenWidth(55),
    height: responsiveScreenHeight(7),
    justifyContent: 'space-evenly',
    alignItems: 'center',
  },
  transTxt: {
    height: responsiveScreenHeight(5.5),
    justifyContent: 'flex-end',
  },
  transmission: {
    width: responsiveScreenWidth(32),
    textAlign: 'center',
    height: responsiveScreenHeight(2.5),
    color: '#183338',
    fontWeight: 'bold',
  },
  adTitileContainer: {
    height: responsiveScreenHeight(6),
    justifyContent: 'flex-end',
  },
  adTitile: {
    width: responsiveScreenWidth(23),
    textAlign: 'center',
    height: responsiveScreenHeight(2.5),
    color: '#889897',
  },
  describeTxtContainer: {
    height: responsiveScreenHeight(8),
    justifyContent: 'flex-end',
  },
  describeTxt: {
    width: responsiveScreenWidth(58),
    textAlign: 'center',
    height: responsiveScreenHeight(2.5),
    color: '#889897',
  },
  pickerContainer: {
    justifyContent: 'center',
    alignItems: 'center',
    height: responsiveScreenHeight(20),
  },
  pickerContainerChild: {
    height: responsiveScreenHeight(10),
    width: responsiveScreenWidth(90),
    justifyContent: 'center',
    borderWidth: 1,
    borderRadius: 5,
  },
  locationTxt: {
    fontSize: responsiveFontSize(2.3),
    textAlignVertical: 'center',
    textAlign: 'center',
    width: responsiveScreenWidth(22),
    fontWeight: 'bold',
  },
  pickerMain: {
    height: responsiveScreenHeight(4),
  },
  buttonContainer: {
    height: responsiveScreenHeight(15),
    alignItems: 'center',
  },
  buttonTouchAble: {
    width: responsiveScreenWidth(90),
    height: responsiveScreenHeight(6),
    backgroundColor: '#e4e7ee',
    borderRadius: responsiveHeight(0.8),
    justifyContent: 'center',
    alignItems: 'center',
  },
  buttonTxt: {
    fontSize: responsiveFontSize(2.3),
    fontWeight: 'bold',
    color: 'white',
  },
  colorBlue: {
    borderWidth: 1,
    borderColor: '#279e94',
    width: responsiveScreenWidth(45),
    height: responsiveScreenHeight(6.6),
    justifyContent: 'center',
    alignItems: 'center',
    borderRadius: 3,
  },
  colorBlack: {
    borderWidth: 1,
    borderColor: '#183338',
    width: responsiveScreenWidth(45),
    height: responsiveScreenHeight(6.6),
    justifyContent: 'center',
    alignItems: 'center',
    borderRadius: 3,
  },
  itemBlueColor: {
    color: '#279e94',
    fontSize: responsiveFontSize(2),
  },
  itemBlackColor: {
    color: '#183338',
    fontSize: responsiveFontSize(2),
  },
  typeContainer: {
    height: responsiveScreenHeight(7),
    justifyContent: 'flex-end',
  },
  typeTxt: {
    width: responsiveScreenWidth(18),
    textAlign: 'center',
    height: responsiveScreenHeight(2.9),
    color: '#183338',
    fontWeight: 'bold',
  },
  mobilePhonesDropDownContainer: {
    justifyContent: 'center',
    alignItems: 'center',
  },
  mobilePhonesDropDownTouchAbleParent: {
    borderWidth: 1,
    width: responsiveScreenWidth(92),
    height: responsiveScreenHeight(10.5),
    borderRadius: 5,
  },
  mobilePhonesDropDownTextContainer: {
    flexDirection: 'column',
    height: responsiveScreenHeight(10.5),
    justifyContent: 'center',
    marginHorizontal: responsiveScreenWidth(6),
  },
  make: {
    fontWeight: 'bold',
    fontSize: responsiveFontSize(2),
  },
  mobilePhonesDropDownSelectedValue: {
    fontSize: responsiveFontSize(2),
    marginVertical: responsiveHeight(0.4),
    width: responsiveScreenWidth(67),
  },
  mobilePhonesDropDownIconContainer: {
    justifyContent: 'center',
    alignItems: 'flex-end',
  },
  installmentDropDownContainer: {
    justifyContent: 'flex-end',
    alignItems: 'center',
    height: responsiveScreenHeight(15),
  },
  registerTxt: {
    width: responsiveScreenWidth(28),
    textAlign: 'center',
    height: responsiveScreenHeight(2.4),
    color: '#183338',
    fontWeight: 'bold',
  },
  installmentTxtSelectorContainer: {
    flexDirection: 'row',
    width: responsiveScreenWidth(55),
    height: responsiveScreenHeight(7),
    justifyContent: 'space-evenly',
    alignItems: 'center',
  },
  yearTxt: {
    width: responsiveScreenWidth(18),
    textAlign: 'center',
    height: responsiveScreenHeight(5),
    textAlignVertical: 'bottom',
    color: '#889897',
    fontWeight: 'bold',
  },
  drivenTxt: {
    width: responsiveScreenWidth(30),
    textAlign: 'center',
    textAlignVertical: 'bottom',
    height: responsiveScreenHeight(7),
    color: '#889897',
    fontWeight: 'bold',
  },
  downTxtContainer: {
    height: responsiveScreenHeight(7),
    justifyContent: 'flex-end',
  },
  downTxt: {
    width: responsiveScreenWidth(35),
    textAlign: 'center',
    height: responsiveScreenWidth(5),
    color: '#889897',
  },
  monthTxt: {
    width: responsiveScreenWidth(43),
    textAlign: 'center',
    height: responsiveScreenHeight(3),
    color: '#889897',
  },
  mainFlatList: {
    width: responsiveScreenWidth(95),
    marginHorizontal: responsiveScreenWidth(4),
  },
  showImgesContainer: {
    borderWidth: 0.3,
    borderColor: '#b3b3b3',
    width: responsiveScreenWidth(92),
    height: responsiveScreenHeight(25),
    backgroundColor: '#fafafa',
  },
  uploadHeadingAndIconContainer: {
    flexDirection: 'row',
    width: responsiveScreenWidth(86),
    height: responsiveScreenHeight(6),
    alignItems: 'center',
  },
  uploadHeading: {
    color: '#052d32',
    fontWeight: 'bold',
  },
  rightArrowIcon: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'flex-end',
  },
  scrollV: {
    flex: 1,
    marginHorizontal: responsiveScreenWidth(1),
  },
  allImges: {
    width: responsiveScreenWidth(20),
    height: responsiveScreenHeight(12),
    borderRadius: 8,
  },
  bottomHeadingContainer: {
    height: 50,
    width: 310,
    justifyContent: 'center',
    alignSelf: 'center',
  },
  bottomHeading: {
    fontSize: 13,
    color: '#0e3133',
  },
});
