export const data = [
  {name: 'Panasonic'},
  {name: 'QMobile'},
  {name: 'Realme'},
  {name: 'Rivo'},
  {name: 'Samsung Mobile'},
  {name: 'Sony'},
  {name: 'Sony Ericsson'},
  {name: 'Tecno'},
  {name: 'Vivo'},
  {name: 'VOICE'},
  {name: 'Xiaomi'},
  {name: 'Zte'},
  {name: 'Other Mobiles'},
  {name: 'Haier'},
  {name: 'Honor'},
  {name: 'HTC'},
  {name: 'Huawei'},
  {name: 'iNew'},
  {name: 'Infinix'},
  {name: 'Lava'},
  {name: 'Lenovo'},
  {name: 'LG'},
  {name: 'Meizu'},
  {name: 'Mobilink JazzX'},
  {name: 'Motorola'},
  {name: 'Nokia'},
  {name: 'One Plus'},
  {name: 'Acer'},
  {name: 'Alcatel'},
  {name: 'Apple iPhone'},
  {name: 'Asus'},
  {name: 'BlackBerry'},
  {name: 'Calme'},
  {name: 'Club'},
  {name: 'G Five'},
  {name: 'Google'},
  {name: 'Gright'},
];
