export const data = [
  {name: 'Audi'},
  {name: 'BMW'},
  {name: 'Changan'},
  {name: 'Chevrolet'},
  {name: 'Classic & Antiques'},
  {name: 'Daewoo'},
  {name: 'Daihatus'},
  {name: 'FAW'},
  {name: 'Honda'},
  {name: 'Hyundai'},
  {name: 'Isuzu'},
  {name: 'JAC'},
  {name: 'KIA'},
  {name: 'Land Rover'},
  {name: 'Lexus'},
  {name: 'Mazda'},
  {name: 'Mercedes'},
  {name: 'Mitsubishi'},
  {name: 'Nissan'},
  {name: 'Porsche'},
  {name: 'Proton'},
  {name: 'Prince'},
  {name: 'Range Rover'},
  {name: 'Renault'},
  {name: 'Nissan'},
  {name: 'Subaru'},
  {name: 'Suzuki'},
  {name: 'Toyota'},
  {name: 'Volkswagen'},
  {name: 'United'},
  {name: 'Other Brands'},
];
